from dotenv import load_dotenv
import os

load_dotenv()

class Config:
  SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
  SQLALCHEMY_TRACK_MODIFICATIONS= os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")
  SECRET_KEY=os.getenv("SECRET_KEY")
  JWT_TOKEN_SECRET=os.getenv("JWT_TOKEN_SECRET")
  JWT_REFRESH_SECRET=os.getenv("JWT_REFRESH_SECRET")
  JWT_ALGO=os.getenv("SQLALCHEMY_DATABASE_URI")
  JWT_TOKEN_LOCATION=os.getenv("SQLALCHEMY_DATABASE_URI")
  JWT_EXPIRE=os.getenv("SQLALCHEMY_DATABASE_URI")